# Generated by Django 5.1.15 on 2026-02-23 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(db_index=True, max_length=100)),
                ('mode', models.CharField(choices=[('invitation', 'Invitation'), ('request', 'Request')], max_length=20)),
                ('initiator_type', models.CharField(choices=[('user', 'User'), ('account', 'Account'), ('membership_actor', 'Membership Actor'), ('system', 'System')], max_length=20)),
                ('initiator_id', models.UUIDField(help_text='User UUID or Membership UUID')),
                ('initiator_context', models.JSONField(default=dict, help_text='ActorContext.to_dict() snapshot at creation')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('account', 'Account'), ('membership_actor', 'Membership Actor'), ('system', 'System')], max_length=20)),
                ('target_id', models.UUIDField(help_text='User UUID or Account UUID')),
                ('context_type', models.CharField(choices=[('platform', 'Platform'), ('business', 'Business'), ('user', 'User')], db_index=True, max_length=20)),
                ('context_id', models.UUIDField(blank=True, db_index=True, help_text='Account UUID. NULL for user context.', null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('invalidated', 'Invalidated')], db_index=True, default='created', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('form_response_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('outcome_executed', models.BooleanField(default=False)),
                ('outcome_executed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_transactions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_context', models.JSONField(default=dict)),
                ('previous_status', models.CharField(blank=True, choices=[('created', 'Created'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('invalidated', 'Invalidated')], max_length=20)),
                ('new_status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('invalidated', 'Invalidated')], max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transaction.transaction')),
            ],
            options={
                'db_table': 'transaction_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_dd72b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['context_type', 'context_id', 'status'], name='transaction_context_104ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['initiator_type', 'initiator_id'], name='transaction_initiat_abb007_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['target_type', 'target_id'], name='transaction_target__4aa04f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['expires_at'], name='transaction_expires_d6d676_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'outcome_executed'], name='transaction_status_943fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('context_type', 'user'), ('context_id__isnull', False), _connector='OR'), name='txn_context_id_required_for_account_contexts'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction', 'timestamp'], name='transaction_transac_45974c_idx'),
        ),
    ]
