# Generated by Django 5.1.15 on 2026-02-24 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='info_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='info_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_requested_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='info_requested_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='info_requested_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='form_response_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('invalidated', 'Invalidated'), ('info_requested', 'Info Requested')], db_index=True, default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('invalidated', 'Invalidated'), ('info_requested', 'Info Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('invalidated', 'Invalidated'), ('info_requested', 'Info Requested')], max_length=20),
        ),
    ]
