# Generated by Django 5.1.15 on 2026-03-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_transactionformmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="transactionformmapping",
            options={
                "verbose_name": "transaction form mapping",
                "verbose_name_plural": "transaction form mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="transactionlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "transaction log",
                "verbose_name_plural": "transaction logs",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("pending_review", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("denied", "Denied"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("dismissed", "Dismissed"),
                    ("invalidated", "Invalidated"),
                    ("info_requested", "Info Requested"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("pending_review", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("denied", "Denied"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("dismissed", "Dismissed"),
                    ("invalidated", "Invalidated"),
                    ("info_requested", "Info Requested"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("pending_review", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("denied", "Denied"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("dismissed", "Dismissed"),
                    ("invalidated", "Invalidated"),
                    ("info_requested", "Info Requested"),
                ],
                max_length=20,
            ),
        ),
    ]
