# Generated by Django 5.1.15 on 2026-03-12 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicesession",
            options={
                "ordering": ["-last_activity"],
                "verbose_name": "device session",
                "verbose_name_plural": "device sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="emailverificationtoken",
            options={
                "verbose_name": "email verification token",
                "verbose_name_plural": "email verification tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="oauthconnection",
            options={
                "verbose_name": "OAuth connection",
                "verbose_name_plural": "OAuth connections",
            },
        ),
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={
                "verbose_name": "password reset token",
                "verbose_name_plural": "password reset tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="refreshtoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "refresh token",
                "verbose_name_plural": "refresh tokens",
            },
        ),
        migrations.AlterUniqueTogether(
            name="devicesession",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="oauthconnection",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="devicesession",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"),
                name="auth_device_session_user_device_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthconnection",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_uid"), name="auth_oauth_provider_uid_uniq"
            ),
        ),
    ]
