# Generated by Django 5.1.15 on 2026-04-07 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_unique_constraints_and_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceOTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'governance OTP token',
                'verbose_name_plural': 'governance OTP tokens',
                'db_table': 'auth_governance_otp',
                'indexes': [models.Index(fields=['user', 'is_used', 'expires_at'], name='auth_govern_user_id_0efaa4_idx'), models.Index(fields=['code', 'email', 'is_used'], name='auth_govern_code_ae62b0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('user',), name='one_active_governance_otp_per_user')],
            },
        ),
    ]
