# Generated by Django 5.1.15 on 2026-03-12 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "notification log",
                "verbose_name_plural": "notification logs",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationpreference",
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "notification_type"), name="notifpref_user_type_uniq"
            ),
        ),
    ]
