# Generated by Django 5.1.15 on 2026-03-28 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_unique_constraint_and_verbose_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationpreference",
            name="notifpref_user_type_uniq",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="scope_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Null for user scope, UUID for org scope",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("business", "Business"),
                    ("platform", "Platform"),
                ],
                db_index=True,
                default="user",
                help_text="Isolation scope: user (personal), business, or platform",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="scope_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Null for user scope, UUID for org scope",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("business", "Business"),
                    ("platform", "Platform"),
                ],
                db_index=True,
                default="user",
                help_text="Isolation scope: user (global default), business, or platform",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["scope_type", "scope_id", "user", "created_at"],
                name="notiflog_scope_user_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["scope_type", "scope_id", "created_at"],
                name="notiflog_scope_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["user", "notification_type", "scope_type", "scope_id"],
                name="notifpref_user_type_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scope_type", "user"), ("scope_id__isnull", False), _connector="OR"
                ),
                name="notiflog_scope_id_required_for_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_id__isnull", False)),
                fields=("user", "notification_type", "scope_type", "scope_id"),
                name="notifpref_user_type_scope_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_id__isnull", True)),
                fields=("user", "notification_type", "scope_type"),
                name="notifpref_user_type_global_uniq",
            ),
        ),
    ]
