# Generated by Django 5.2.10 on 2026-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_email_ci_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["referred_by"], name="users_referred_by_idx"),
        ),
    ]
