# Generated by Django 5.1.15 on 2026-02-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_users_referred_by_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="verified_only_if_active",
        ),
    ]
