# Generated by Django 5.1.15 on 2026-02-10 11:25

import uuid

from django.db import migrations, models


def convert_id_type_for_postgres(apps, schema_editor):
    """Convert User.id from bigint to uuid on PostgreSQL.

    PostgreSQL cannot cast bigint to uuid directly (even on empty tables).
    Migration 0005 already cleared all data, so we manually ALTER the column
    types before Django's state-only AlterField.

    On SQLite this recreates the table via schema_editor (Django's standard
    approach for SQLite ALTER operations).
    """
    User = apps.get_model("users", "User")

    if schema_editor.connection.vendor == "postgresql":
        _convert_postgres(schema_editor)
    else:
        # For SQLite, use Django's schema editor which recreates the table
        old_field = models.BigAutoField(primary_key=True, serialize=False)
        new_field = models.UUIDField(
            default=uuid.uuid4,
            editable=False,
            primary_key=True,
            serialize=False,
        )
        old_field.set_attributes_from_name("id")
        new_field.set_attributes_from_name("id")
        old_field.model = User
        new_field.model = User
        schema_editor.alter_field(User, old_field, new_field)


def _convert_postgres(schema_editor):
    """Handle the full bigint-to-uuid conversion on PostgreSQL.

    Steps:
    1. Drop all FK constraints referencing users.id
    2. Drop CHECK constraints on users that compare id with other columns
    3. Drop PK constraint
    4. Convert users.id from bigint to uuid
    5. Convert users.referred_by_id from bigint to uuid
    6. Convert all FK columns in other tables from bigint to uuid
    7. Re-add PK, CHECK, and FK constraints
    """
    with schema_editor.connection.cursor() as cursor:
        # 1. Find all FK constraints referencing users.id
        cursor.execute("""
            SELECT con.conname, rel.relname, att.attname
            FROM pg_constraint con
            JOIN pg_class rel ON con.conrelid = rel.oid
            JOIN pg_attribute att
                ON att.attrelid = con.conrelid
                AND att.attnum = ANY(con.conkey)
            JOIN pg_class ref ON con.confrelid = ref.oid
            WHERE con.contype = 'f'
                AND ref.relname = 'users'
        """)
        fk_constraints = cursor.fetchall()

        # 2. Find CHECK constraints on users table
        cursor.execute("""
            SELECT con.conname
            FROM pg_constraint con
            JOIN pg_class rel ON con.conrelid = rel.oid
            WHERE rel.relname = 'users' AND con.contype = 'c'
        """)
        check_constraints = cursor.fetchall()

        # 3. Drop CHECK constraints (e.g. no_self_referral: id = referred_by_id)
        for (constraint_name,) in check_constraints:
            cursor.execute(
                f'ALTER TABLE "users" DROP CONSTRAINT "{constraint_name}"'
            )

        # 4. Drop FK constraints
        for constraint_name, table_name, _ in fk_constraints:
            cursor.execute(
                f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}"'
            )

        # 5. Drop PK constraint
        cursor.execute("""
            SELECT con.conname
            FROM pg_constraint con
            JOIN pg_class rel ON con.conrelid = rel.oid
            WHERE rel.relname = 'users' AND con.contype = 'p'
        """)
        pk_row = cursor.fetchone()
        if pk_row:
            cursor.execute(
                f'ALTER TABLE "users" DROP CONSTRAINT "{pk_row[0]}"'
            )

        # 6. Convert users.id: drop identity, change type, set default
        cursor.execute(
            'ALTER TABLE "users" ALTER COLUMN "id" DROP IDENTITY IF EXISTS'
        )
        cursor.execute(
            'ALTER TABLE "users" ALTER COLUMN "id" '
            "TYPE uuid USING gen_random_uuid()"
        )
        cursor.execute(
            'ALTER TABLE "users" ALTER COLUMN "id" '
            "SET DEFAULT gen_random_uuid()"
        )
        cursor.execute('ALTER TABLE "users" ALTER COLUMN "id" SET NOT NULL')

        # 7. Convert users.referred_by_id from bigint to uuid
        cursor.execute(
            'ALTER TABLE "users" ALTER COLUMN "referred_by_id" '
            "TYPE uuid USING NULL::uuid"
        )

        # 8. Re-add PK
        cursor.execute('ALTER TABLE "users" ADD PRIMARY KEY ("id")')

        # 9. Re-add CHECK constraints with updated types
        cursor.execute("""
            ALTER TABLE "users" ADD CONSTRAINT "no_self_referral"
            CHECK (NOT (id = referred_by_id AND referred_by_id IS NOT NULL))
        """)

        # 10. Re-add self-referencing FK for referred_by_id
        cursor.execute("""
            ALTER TABLE "users" ADD CONSTRAINT
            "users_referred_by_id_985c1072_fk_users_id"
            FOREIGN KEY ("referred_by_id") REFERENCES "users" ("id")
            DEFERRABLE INITIALLY DEFERRED
        """)

        # 11. Convert FK columns in other tables and re-add their constraints
        for constraint_name, table_name, column_name in fk_constraints:
            # Skip the self-referencing FK (already handled above)
            if table_name == "users" and column_name == "referred_by_id":
                continue
            cursor.execute(
                f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" '
                f"TYPE uuid USING NULL::uuid"
            )
            cursor.execute(
                f'ALTER TABLE "{table_name}" ADD CONSTRAINT "{constraint_name}" '
                f'FOREIGN KEY ("{column_name}") REFERENCES "users" ("id") '
                f"DEFERRABLE INITIALLY DEFERRED"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_prepare_uuid_migration"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    convert_id_type_for_postgres,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
