# Generated by Django 5.1.15 on 2026-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_explore_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this profile is publicly visible to other users.",
            ),
        ),
    ]
