# Generated by Django 5.1.15 on 2026-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userprofile_visibility_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of consecutive failed login attempts."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Account locked until this time due to too many failed login attempts.",
                null=True,
            ),
        ),
    ]
