# Generated by Django 5.1.15 on 2026-01-26 23:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "actor_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the actor (user ID)",
                        null=True,
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email snapshot at time of action",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Administrator"),
                            ("system", "System"),
                            ("anonymous", "Anonymous"),
                        ],
                        default="user",
                        help_text="Type of actor",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auth.login.success", "Login Success"),
                            ("auth.login.failed", "Login Failed"),
                            ("auth.logout", "Logout"),
                            ("auth.token.refresh", "Token Refresh"),
                            ("auth.password.changed", "Password Changed"),
                            (
                                "auth.password.reset_requested",
                                "Password Reset Requested",
                            ),
                            (
                                "auth.password.reset_completed",
                                "Password Reset Completed",
                            ),
                            ("auth.verification.sent", "Verification Sent"),
                            ("auth.email.verified", "Email Verified"),
                            ("auth.oauth.linked", "OAuth Account Linked"),
                            ("auth.oauth.unlinked", "OAuth Account Unlinked"),
                            ("auth.session.created", "Session Created"),
                            ("auth.session.revoked", "Session Revoked"),
                            ("auth.sessions.revoked_all", "All Sessions Revoked"),
                            ("user.created", "User Created"),
                            ("user.updated", "User Updated"),
                            ("user.deactivated", "User Deactivated"),
                            ("user.reactivated", "User Reactivated"),
                            ("user.deleted", "User Deleted"),
                            ("user.profile.updated", "Profile Updated"),
                            ("user.avatar.changed", "Avatar Changed"),
                            ("user.avatar.deleted", "Avatar Deleted"),
                            (
                                "notification.preference.updated",
                                "Notification Preference Updated",
                            ),
                            ("email.template.created", "Email Template Created"),
                            ("email.template.updated", "Email Template Updated"),
                            ("admin.user.updated", "Admin Updated User"),
                            ("admin.user.deactivated", "Admin Deactivated User"),
                            ("admin.settings.changed", "Admin Changed Settings"),
                            ("data.exported", "Data Exported"),
                            ("data.sensitive.accessed", "Sensitive Data Accessed"),
                        ],
                        db_index=True,
                        help_text="Action performed",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of resource affected (e.g., 'User', 'DeviceSession')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of affected resource",
                        null=True,
                    ),
                ),
                (
                    "resource_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable resource representation",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="Client user agent string"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Correlation ID for request tracing",
                        max_length=36,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("denied", "Permission Denied"),
                        ],
                        db_index=True,
                        default="success",
                        help_text="Action outcome",
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured details",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Before/after values for updates",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor_id", "-timestamp"], name="audit_actor_time_idx"
                    ),
                    models.Index(
                        fields=["action", "-timestamp"], name="audit_action_time_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_resource_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="audit_timestamp_idx"),
                ],
            },
        ),
    ]
