# Generated by Django 5.1.15 on 2026-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login.success", "Login Success"),
                    ("auth.login.failed", "Login Failed"),
                    ("auth.logout", "Logout"),
                    ("auth.token.refresh", "Token Refresh"),
                    ("auth.password.changed", "Password Changed"),
                    ("auth.password.reset_requested", "Password Reset Requested"),
                    ("auth.password.reset_completed", "Password Reset Completed"),
                    ("auth.verification.sent", "Verification Sent"),
                    ("auth.email.verified", "Email Verified"),
                    ("auth.oauth.linked", "OAuth Account Linked"),
                    ("auth.oauth.unlinked", "OAuth Account Unlinked"),
                    ("auth.session.created", "Session Created"),
                    ("auth.session.revoked", "Session Revoked"),
                    ("auth.sessions.revoked_all", "All Sessions Revoked"),
                    ("user.created", "User Created"),
                    ("user.updated", "User Updated"),
                    ("user.deactivated", "User Deactivated"),
                    ("user.reactivated", "User Reactivated"),
                    ("user.deleted", "User Deleted"),
                    ("user.profile.updated", "Profile Updated"),
                    ("user.avatar.changed", "Avatar Changed"),
                    ("user.avatar.deleted", "Avatar Deleted"),
                    (
                        "notification.preference.updated",
                        "Notification Preference Updated",
                    ),
                    ("email.template.created", "Email Template Created"),
                    ("email.template.updated", "Email Template Updated"),
                    ("admin.user.updated", "Admin Updated User"),
                    ("admin.user.deactivated", "Admin Deactivated User"),
                    ("admin.settings.changed", "Admin Changed Settings"),
                    ("data.exported", "Data Exported"),
                    ("data.sensitive.accessed", "Sensitive Data Accessed"),
                    ("org.platform.configured", "Platform Configured"),
                    ("org.platform.settings_updated", "Platform Settings Updated"),
                    ("org.platform.profile_updated", "Platform Profile Updated"),
                    ("org.business.created", "Business Created"),
                    ("org.business.updated", "Business Updated"),
                    ("org.business.suspended", "Business Suspended"),
                    ("org.business.reactivated", "Business Reactivated"),
                    ("org.business.archived", "Business Archived"),
                    ("org.business.deleted", "Business Deleted"),
                    ("org.business.slug_changed", "Business Slug Changed"),
                    ("org.business.profile_updated", "Business Profile Updated"),
                    ("org.verification.approved", "Verification Approved"),
                    ("org.verification.rejected", "Verification Rejected"),
                    (
                        "org.ownership.transfer_initiated",
                        "Ownership Transfer Initiated",
                    ),
                ],
                db_index=True,
                help_text="Action performed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of the actor (user ID as string)",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of affected resource (as string)",
                max_length=36,
                null=True,
            ),
        ),
    ]
