# Generated by Django 5.1.15 on 2026-02-26 09:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., hero_text)", max_length=255
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for admin UI", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Globally unique identifier (among non-deleted)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Block purpose"),
                ),
                (
                    "block_type",
                    models.CharField(
                        help_text="Categorization (text, media, composite, repeater)",
                        max_length=50,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="Field definitions — types, validation, required flags"
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveIntegerField(
                        default=1, help_text="Auto-incremented on every schema change"
                    ),
                ),
                (
                    "default_content",
                    models.JSONField(
                        blank=True,
                        help_text="Default values to pre-populate new placements",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Tags, categorization", null=True
                    ),
                ),
                (
                    "ui_config",
                    models.JSONField(
                        blank=True,
                        help_text="Rendering hints — component name, CSS classes, layout rules",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Template",
                "verbose_name_plural": "Block Templates",
                "db_table": "cms_block_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("platform", "Platform"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        help_text="Which account type owns this folder",
                        max_length=20,
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of owning account record",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Folder display name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=100),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Full materialized path (e.g., /images/heroes/2026/)",
                        max_length=1000,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent folder for nesting. CASCADE applies to hard deletes. For soft deletes, CMSMediaService.delete_folder must recursively soft-delete children as defense-in-depth.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.mediafolder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Folder",
                "verbose_name_plural": "Media Folders",
                "db_table": "cms_media_folder",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("platform", "Platform"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("owner_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Storage path/key (e.g., platform/images/hero-banner.png)",
                        max_length=500,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original upload filename", max_length=255
                    ),
                ),
                ("mime_type", models.CharField(help_text="MIME type", max_length=100)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="EXIF data, custom tags, processing info",
                        null=True,
                    ),
                ),
                (
                    "is_tombstoned",
                    models.BooleanField(
                        default=False,
                        help_text="Marked for removal but still accessible (published refs exist)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Containing folder (null = root)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="cms.mediafolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "db_table": "cms_media_file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Page title", max_length=255)),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Internal description"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="URL path relative to site (e.g., /about)",
                        max_length=500,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        help_text="Categorization (landing, content, legal, blog_post)",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="SEO title, description, OG tags, structured data",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the page was last published",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Ordering within the site's page list"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If true, admins cannot delete or hide this page",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Admin can toggle false ONLY if is_required=False",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Page",
                "verbose_name_plural": "CMS Pages",
                "db_table": "cms_page",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageSectionPlacement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional admin-friendly label",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Position within the page"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If true, admin cannot hide this section",
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "config_overrides",
                    models.JSONField(
                        blank=True,
                        help_text="Per-placement overrides (background, spacing, etc.)",
                        null=True,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page this section is placed on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_placements",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Section Placement",
                "verbose_name_plural": "Page Section Placements",
                "db_table": "cms_page_section_placement",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionBlockPlacement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional admin-friendly label",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position within the section"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="If true, admin cannot hide this block"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "config_overrides",
                    models.JSONField(
                        blank=True, help_text="Per-placement overrides", null=True
                    ),
                ),
                (
                    "schema_version_validated",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="BlockTemplate.schema_version this was last validated against",
                    ),
                ),
                (
                    "draft_content",
                    models.JSONField(
                        blank=True,
                        help_text="Working copy — admin edits this. Pre-populated from default_content",
                        null=True,
                    ),
                ),
                (
                    "published_content",
                    models.JSONField(
                        blank=True,
                        help_text="Frozen live copy — set only on page publish. Public API serves this",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section_placement",
                    models.ForeignKey(
                        help_text="The section placement this block belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_placements",
                        to="cms.pagesectionplacement",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The block template defining the schema",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="cms.blocktemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Block Placement",
                "verbose_name_plural": "Section Block Placements",
                "db_table": "cms_section_block_placement",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MediaUsage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        help_text="Which field in the block's content references this file",
                        max_length=100,
                    ),
                ),
                (
                    "content_layer",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        help_text="Which content JSONB holds this reference (draft or published)",
                        max_length=20,
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        help_text="The referenced file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="cms.mediafile",
                    ),
                ),
                (
                    "block_placement",
                    models.ForeignKey(
                        help_text="The block placement containing the reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_usages",
                        to="cms.sectionblockplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Usage",
                "verbose_name_plural": "Media Usages",
                "db_table": "cms_media_usage",
            },
        ),
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_snapshot",
                    models.JSONField(
                        help_text="Full copy of draft_content at this point"
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Auto-incrementing per block placement"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("draft_save", "Draft Save"),
                            ("publish", "Publish"),
                            ("rollback", "Rollback"),
                            ("import", "Import"),
                        ],
                        help_text="What triggered this version",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Optional change description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Who made this change",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cms_content_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block_placement",
                    models.ForeignKey(
                        help_text="The block placement this version belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="cms.sectionblockplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Version",
                "verbose_name_plural": "Content Versions",
                "db_table": "cms_content_version",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="SectionTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., hero_banner)", max_length=255
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for admin UI", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Globally unique identifier (among non-deleted)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Section purpose"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        help_text="Categorization (header, content, footer, sidebar)",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Tags, categorization", null=True
                    ),
                ),
                (
                    "ui_config",
                    models.JSONField(
                        blank=True,
                        help_text="UI rendering hints — component name, layout mode, CSS classes",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Template",
                "verbose_name_plural": "Section Templates",
                "db_table": "cms_section_template",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="pagesectionplacement",
            name="template",
            field=models.ForeignKey(
                help_text="The section template being placed",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="cms.sectiontemplate",
            ),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("platform", "Platform"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        help_text="Which account type owns this site",
                        max_length=20,
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of owning account record (PlatformAccount.id or BusinessAccount.id)",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the site", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-safe identifier", max_length=100),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Associated domain",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Internal description"
                    ),
                ),
                (
                    "default_locale",
                    models.CharField(
                        default="en", help_text="Default language code", max_length=10
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="SEO defaults, theme settings, global config",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the site is live"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Designated homepage for this site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.page",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS Site",
                "verbose_name_plural": "CMS Sites",
                "db_table": "cms_site",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="page",
            name="site",
            field=models.ForeignKey(
                help_text="The site this page belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="cms.site",
            ),
        ),
        migrations.CreateModel(
            name="CMSApiKey",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive label (e.g., Production Website)",
                        max_length=255,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars of the key (for display/identification)",
                        max_length=16,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the key. Never store plaintext",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "allowed_origins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed Origin/Referer values. Empty = no origin restriction",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration. Null = never expires",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Auto-updated on each use", null=True
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=60, help_text="Max requests per minute"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site this key grants access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="cms.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS API Key",
                "verbose_name_plural": "CMS API Keys",
                "db_table": "cms_api_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="blocktemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="unique_block_template_slug_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediafolder",
            constraint=models.UniqueConstraint(
                fields=("owner_type", "owner_id", "parent", "slug"),
                name="unique_cms_folder_slug_per_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["owner_type", "owner_id", "folder"],
                name="cms_media_f_owner_t_d5fb93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["mime_type"], name="cms_media_f_mime_ty_102b79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["is_tombstoned"], name="cms_media_f_is_tomb_028a1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionblockplacement",
            index=models.Index(
                fields=["template"], name="cms_section_templat_c4217d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionblockplacement",
            index=models.Index(fields=["status"], name="cms_section_status_bc3518_idx"),
        ),
        migrations.AddConstraint(
            model_name="sectionblockplacement",
            constraint=models.UniqueConstraint(
                fields=("section_placement", "order"),
                name="unique_cms_block_order_per_section",
            ),
        ),
        migrations.AddIndex(
            model_name="mediausage",
            index=models.Index(
                fields=["media_file"], name="cms_media_u_media_f_5040bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediausage",
            index=models.Index(
                fields=["block_placement"], name="cms_media_u_block_p_f0d566_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediausage",
            index=models.Index(
                fields=["content_layer"], name="cms_media_u_content_6d1890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentversion",
            index=models.Index(
                fields=["block_placement", "-version_number"],
                name="cms_content_block_p_6ae8d8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectiontemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="unique_section_template_slug_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesectionplacement",
            constraint=models.UniqueConstraint(
                fields=("page", "order"), name="unique_cms_section_order_per_page"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["owner_type", "owner_id"], name="cms_site_owner_t_0944a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["is_active"], name="cms_site_is_acti_21d955_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("owner_type", "owner_id", "slug"),
                name="unique_cms_site_slug_per_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["site", "status"], name="cms_page_site_id_4f1e23_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("site", "slug"),
                name="unique_cms_page_slug_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("site", "path"),
                name="unique_cms_page_path_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("site", "order"),
                name="unique_cms_page_order_per_site",
            ),
        ),
        migrations.AddIndex(
            model_name="cmsapikey",
            index=models.Index(fields=["site"], name="cms_api_key_site_id_f00a4b_idx"),
        ),
    ]
