# Generated by Django 5.1.15 on 2026-03-13 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mediafolder",
            name="unique_cms_folder_slug_per_parent",
        ),
        migrations.AddConstraint(
            model_name="mediafolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("owner_type", "owner_id", "parent", "slug"),
                name="unique_cms_folder_slug_per_parent",
            ),
        ),
    ]
