# Generated by Django 5.1.15 on 2026-03-29 13:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_remove_mediafolder_unique_cms_folder_slug_per_parent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Auto-activate for new orgs when CMS is enabled.",
            ),
        ),
        migrations.AddField(
            model_name="blocktemplate",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("platform", "Platform"),
                    ("business", "Business"),
                    ("all", "All"),
                ],
                db_index=True,
                default="all",
                help_text="Which organization types can activate and use this template.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sectiontemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Auto-activate for new orgs when CMS is enabled.",
            ),
        ),
        migrations.AddField(
            model_name="sectiontemplate",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("platform", "Platform"),
                    ("business", "Business"),
                    ("all", "All"),
                ],
                db_index=True,
                default="all",
                help_text="Which organization types can activate and use this template.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BlockTemplateActivation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("platform", "Platform"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        help_text="Organization type (platform or business)",
                        max_length=20,
                    ),
                ),
                (
                    "org_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the organization account"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Org can deactivate templates without deleting the record",
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        help_text="Who activated this template for the org",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_block_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The canonical block template being activated",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="cms.blocktemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Template Activation",
                "verbose_name_plural": "Block Template Activations",
                "db_table": "cms_block_template_activation",
                "indexes": [
                    models.Index(
                        fields=["org_type", "org_id", "is_active"],
                        name="cms_block_t_org_typ_97f01e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "org_type", "org_id"),
                        name="unique_block_activation_per_org",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SectionTemplateActivation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("platform", "Platform"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        help_text="Organization type (platform or business)",
                        max_length=20,
                    ),
                ),
                (
                    "org_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the organization account"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Org can deactivate templates without deleting the record",
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        help_text="Who activated this template for the org",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_section_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The canonical section template being activated",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="cms.sectiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Template Activation",
                "verbose_name_plural": "Section Template Activations",
                "db_table": "cms_section_template_activation",
                "indexes": [
                    models.Index(
                        fields=["org_type", "org_id", "is_active"],
                        name="cms_section_org_typ_f1d3f7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "org_type", "org_id"),
                        name="unique_section_activation_per_org",
                    )
                ],
            },
        ),
        # Backfill: existing templates get is_default=True so they auto-provision
        migrations.RunPython(
            lambda apps, se: (
                apps.get_model("cms", "SectionTemplate")
                .objects.filter(is_default=False)
                .update(is_default=True),
                apps.get_model("cms", "BlockTemplate")
                .objects.filter(is_default=False)
                .update(is_default=True),
            ),
            migrations.RunPython.noop,
        ),
    ]
