# Generated by Django 5.1.15 on 2026-03-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0009_seed_visibility_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending_approval", "Pending Approval"),
                    ("suspended", "Suspended"),
                    ("left", "Left"),
                    ("removed", "Removed"),
                    ("banned", "Banned"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
