# Generated by Django 5.1.15 on 2026-03-13 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0010_update_membership_status_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="role",
            name="unique_role_name_per_account",
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("account_type", "account_id", "name"),
                name="unique_role_name_per_account",
            ),
        ),
    ]
