# Generated by Django 5.1.15 on 2026-04-07 07:50

from django.db import migrations


def fix_scope(apps, schema_editor):
    """Add global_only to can_approve_business_creation applicable_scopes."""
    Permission = apps.get_model("rbac", "Permission")
    try:
        perm = Permission.objects.get(code="can_approve_business_creation")
        if "global_only" not in perm.applicable_scopes:
            perm.applicable_scopes.append("global_only")
            perm.save(update_fields=["applicable_scopes"])
    except Permission.DoesNotExist:
        pass  # Permission not seeded yet — will be created with correct scopes


def revert_scope(apps, schema_editor):
    """Remove global_only from can_approve_business_creation applicable_scopes."""
    Permission = apps.get_model("rbac", "Permission")
    try:
        perm = Permission.objects.get(code="can_approve_business_creation")
        if "global_only" in perm.applicable_scopes:
            perm.applicable_scopes.remove("global_only")
            perm.save(update_fields=["applicable_scopes"])
    except Permission.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0014_extend_cms_permission_scopes"),
    ]

    operations = [
        migrations.RunPython(fix_scope, revert_scope),
    ]
