# Generated by Django 5.1.15 on 2026-02-23 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Form display name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Form description')),
                ('owner_type', models.CharField(choices=[('system', 'System'), ('platform', 'Platform'), ('business', 'Business')], db_index=True, help_text='Who owns this form template', max_length=20)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of owner account (null for system forms)', null=True)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('business', 'Business')], db_index=True, help_text='Where this form can be used', max_length=20)),
                ('creator_context', models.JSONField(help_text='ActorContext snapshot at creation time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='True if this is the current version')),
                ('is_template_public', models.BooleanField(db_index=True, default=False, help_text='If true, visible in public template library')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Form-level settings (expiry, notifications, etc.)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('forked_from', models.ForeignKey(blank=True, help_text='Template this was forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='forms.formtemplate')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Previous version this was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='forms.formtemplate')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'db_table': 'form_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('form_version', models.PositiveIntegerField(help_text='Form version at submission time')),
                ('submitter_context', models.JSONField(help_text='ActorContext snapshot at submission time')),
                ('data', models.JSONField(help_text='Complete response data as JSON')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processed', 'Processed'), ('void', 'Void'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When response was submitted', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When response was processed', null=True)),
                ('processor_notes', models.TextField(blank=True, default='', help_text='Notes from processor')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_form_responses', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='forms.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
                'db_table': 'form_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text='Machine-readable field identifier', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('currency', 'Currency'), ('rating', 'Rating'), ('boolean', 'Boolean'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('datetime', 'Date & Time'), ('time', 'Time'), ('select', 'Select'), ('radio', 'Radio'), ('multiselect', 'Multi-Select'), ('checkbox_group', 'Checkbox Group'), ('file', 'File'), ('image', 'Image'), ('location', 'Location'), ('repeatable', 'Repeatable Group')], help_text='Field type determining input and validation', max_length=50)),
                ('label', models.CharField(help_text='Field label', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Help text for the field')),
                ('placeholder', models.CharField(blank=True, default='', help_text='Placeholder text', max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Display order (lower first)')),
                ('step_tag', models.CharField(blank=True, db_index=True, default='', help_text='Groups fields into wizard steps', max_length=50)),
                ('section_tag', models.CharField(blank=True, default='', help_text='Visual grouping within a step', max_length=50)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select, radio, etc.')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules (min_length, max_value, etc.)')),
                ('ui_config', models.JSONField(blank=True, default=dict, help_text='UI configuration (width, layout_hint)')),
                ('default_value', models.JSONField(blank=True, help_text='Default value or dynamic token', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Field must have a value')),
                ('is_indexed', models.BooleanField(db_index=True, default=False, help_text='Value goes to typed index table (max 5 per form)')),
                ('is_hidden', models.BooleanField(default=False, help_text='System/internal field, not shown in UI')),
                ('is_readonly', models.BooleanField(default=False, help_text='Displayed but not editable')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'db_table': 'form_field',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IntegerFieldIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, help_text='The field key this value is for', max_length=100)),
                ('value', models.BigIntegerField(help_text='Indexed integer value')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_indexes', to='forms.formresponse')),
            ],
            options={
                'db_table': 'form_integer_field_index',
            },
        ),
        migrations.CreateModel(
            name='TextFieldIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, help_text='The field key this value is for', max_length=100)),
                ('value', models.TextField(help_text='Indexed text value')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_indexes', to='forms.formresponse')),
            ],
            options={
                'db_table': 'form_text_field_index',
            },
        ),
        migrations.CreateModel(
            name='DecimalFieldIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, help_text='The field key this value is for', max_length=100)),
                ('value', models.DecimalField(decimal_places=4, help_text='Indexed decimal value', max_digits=19)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_indexes', to='forms.formresponse')),
            ],
            options={
                'db_table': 'form_decimal_field_index',
                'indexes': [models.Index(fields=['response', 'field_key'], name='form_decima_respons_a30ad8_idx'), models.Index(fields=['field_key', 'value'], name='form_decima_field_k_d22898_idx')],
            },
        ),
        migrations.CreateModel(
            name='DateTimeFieldIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, help_text='The field key this value is for', max_length=100)),
                ('value', models.DateTimeField(help_text='Indexed datetime value')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_indexes', to='forms.formresponse')),
            ],
            options={
                'db_table': 'form_datetime_field_index',
                'indexes': [models.Index(fields=['response', 'field_key'], name='form_dateti_respons_1c3d36_idx'), models.Index(fields=['field_key', 'value'], name='form_dateti_field_k_bd068d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DateFieldIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, help_text='The field key this value is for', max_length=100)),
                ('value', models.DateField(help_text='Indexed date value')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_indexes', to='forms.formresponse')),
            ],
            options={
                'db_table': 'form_date_field_index',
                'indexes': [models.Index(fields=['response', 'field_key'], name='form_date_f_respons_f7313c_idx'), models.Index(fields=['field_key', 'value'], name='form_date_f_field_k_5a5675_idx')],
            },
        ),
        migrations.CreateModel(
            name='BooleanFieldIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, help_text='The field key this value is for', max_length=100)),
                ('value', models.BooleanField(help_text='Indexed boolean value')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_indexes', to='forms.formresponse')),
            ],
            options={
                'db_table': 'form_boolean_field_index',
                'indexes': [models.Index(fields=['response', 'field_key'], name='form_boolea_respons_8cdd9f_idx'), models.Index(fields=['field_key', 'value'], name='form_boolea_field_k_95dd75_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['owner_type', 'owner_id'], name='form_templa_owner_t_079cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['scope', 'status'], name='form_templa_scope_15e7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['is_template_public', 'status'], name='form_templa_is_temp_8f1218_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['owner_type', 'owner_id', 'is_current'], name='form_templa_owner_t_39a5e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(fields=('owner_type', 'owner_id', 'slug', 'version'), name='unique_form_slug_per_owner_version'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['form_template', 'status'], name='form_respon_form_te_3a3468_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['submitted_by', 'status'], name='form_respon_submitt_a8e23a_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['form_template', 'submitted_at'], name='form_respon_form_te_0e7694_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['status', '-submitted_at'], name='form_respon_status_e595d8_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form_template', 'order'], name='form_field_form_te_76956e_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form_template', 'step_tag'], name='form_field_form_te_89a9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form_template', 'is_indexed'], name='form_field_form_te_fb1f64_idx'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form_template', 'field_key'), name='unique_field_key_per_form'),
        ),
        migrations.AddIndex(
            model_name='integerfieldindex',
            index=models.Index(fields=['response', 'field_key'], name='form_intege_respons_653ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='integerfieldindex',
            index=models.Index(fields=['field_key', 'value'], name='form_intege_field_k_a50795_idx'),
        ),
        migrations.AddIndex(
            model_name='textfieldindex',
            index=models.Index(fields=['response', 'field_key'], name='form_text_f_respons_e46058_idx'),
        ),
        migrations.AddIndex(
            model_name='textfieldindex',
            index=models.Index(fields=['field_key', 'value'], name='form_text_f_field_k_7fbf06_idx'),
        ),
    ]
