# Generated by Django 5.1.15 on 2026-02-24 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='context_id',
            field=models.UUIDField(blank=True, help_text='Context account UUID', null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='context_type',
            field=models.CharField(blank=True, default='', help_text='Context type: platform, business, or user', max_length=20),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='info_requested_at',
            field=models.DateTimeField(blank=True, help_text='When additional info was last requested', null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='revision_history',
            field=models.JSONField(default=list, help_text='Previous revision snapshots'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Linked transaction UUID', null=True),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['transaction_id'], name='form_respon_transac_2b7340_idx'),
        ),
    ]
