# Generated by Django 5.1.15 on 2026-03-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_make_system_forms_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booleanfieldindex",
            options={
                "verbose_name": "boolean field index",
                "verbose_name_plural": "boolean field indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="datefieldindex",
            options={
                "verbose_name": "date field index",
                "verbose_name_plural": "date field indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="datetimefieldindex",
            options={
                "verbose_name": "datetime field index",
                "verbose_name_plural": "datetime field indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="decimalfieldindex",
            options={
                "verbose_name": "decimal field index",
                "verbose_name_plural": "decimal field indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="integerfieldindex",
            options={
                "verbose_name": "integer field index",
                "verbose_name_plural": "integer field indexes",
            },
        ),
        migrations.AlterModelOptions(
            name="textfieldindex",
            options={
                "verbose_name": "text field index",
                "verbose_name_plural": "text field indexes",
            },
        ),
    ]
