# Generated by Django 5.1.15 on 2026-03-13 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_add_fieldindex_verbose_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formtemplate",
            name="unique_form_slug_per_owner_version",
        ),
        migrations.AddConstraint(
            model_name="formtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("owner_type", "owner_id", "slug", "version"),
                name="unique_form_slug_per_owner_version",
            ),
        ),
    ]
