# Generated by Django 5.1.15 on 2026-03-09 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('user_user', 'User ↔ User'), ('account_account', 'Account ↔ Account')], db_index=True, max_length=20)),
                ('account_a_type', models.CharField(blank=True, default='', max_length=20)),
                ('account_a_id', models.UUIDField(blank=True, null=True)),
                ('account_b_type', models.CharField(blank=True, default='', max_length=20)),
                ('account_b_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected')], db_index=True, default='active', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnected_connections', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_connections', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'network_connection',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_a', 'user_b', 'status'], name='network_con_user_a__f57507_idx'), models.Index(fields=['account_a_type', 'account_a_id', 'status'], name='network_con_account_a8adf4_idx'), models.Index(fields=['account_b_type', 'account_b_id', 'status'], name='network_con_account_0c7e6a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('connection_type', 'user_user'), ('status', 'active')), fields=('user_a', 'user_b'), name='unique_active_user_connection'), models.UniqueConstraint(condition=models.Q(('connection_type', 'account_account'), ('status', 'active')), fields=('account_a_type', 'account_a_id', 'account_b_type', 'account_b_id'), name='unique_active_account_connection'), models.CheckConstraint(condition=models.Q(models.Q(('connection_type', 'user_user'), _negated=True), models.Q(('user_a__isnull', False), ('user_b__isnull', False)), _connector='OR'), name='user_connection_requires_users'), models.CheckConstraint(condition=models.Q(models.Q(('connection_type', 'account_account'), _negated=True), models.Q(('account_a_id__isnull', False), ('account_b_id__isnull', False)), _connector='OR'), name='account_connection_requires_accounts')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('followee_type', models.CharField(choices=[('business', 'Business'), ('platform', 'Platform')], db_index=True, max_length=20)),
                ('followee_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], db_index=True, default='active', max_length=20)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'network_follow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', 'followee_type', 'followee_id'], name='network_fol_followe_f5b6b0_idx'), models.Index(fields=['followee_type', 'followee_id', 'status'], name='network_fol_followe_1eed7e_idx'), models.Index(fields=['follower', 'status'], name='network_fol_followe_ed3bf5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('follower', 'followee_type', 'followee_id'), name='unique_active_follow')],
            },
        ),
    ]
