# Generated by Django 5.1.15 on 2026-03-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "connection",
                "verbose_name_plural": "connections",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "follow",
                "verbose_name_plural": "follows",
            },
        ),
    ]
