# Generated by Django 5.1.15 on 2026-02-09 09:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("legal_name", models.CharField(max_length=255)),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tax_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "country",
                    models.CharField(help_text="ISO 3166-1 alpha-2", max_length=2),
                ),
                ("legal_address", models.TextField(blank=True, default="")),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("sole_proprietorship", "Sole Proprietorship"),
                            ("partnership", "Partnership"),
                            ("llc", "LLC"),
                            ("corporation", "Corporation"),
                            ("nonprofit", "Nonprofit"),
                            ("cooperative", "Cooperative"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_businesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Account",
                "verbose_name_plural": "Business Accounts",
                "db_table": "business_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flag indicating if record is soft-deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when record was soft-deleted",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        help_text="Singleton enforcement - always 1",
                        unique=True,
                    ),
                ),
                (
                    "is_configured",
                    models.BooleanField(
                        default=False, help_text="Whether initial setup is complete"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Platform-wide settings"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Account",
                "verbose_name_plural": "Platform Accounts",
                "db_table": "platform_account",
            },
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="organization.businessaccount",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="business/logos/%Y/%m/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="business/covers/%Y/%m/"
                    ),
                ),
                ("website", models.URLField(blank=True, default="")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1 employee"),
                            ("2-10", "2-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("500+", "500+ employees"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, help_text="Form Builder extensions"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profiles",
                "db_table": "business_profile",
            },
        ),
        migrations.CreateModel(
            name="BusinessSlugHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("old_slug", models.SlugField(max_length=100, unique=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_history",
                        to="organization.businessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Slug History",
                "verbose_name_plural": "Business Slug Histories",
                "db_table": "business_slug_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformProfile",
            fields=[
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="organization.platformaccount",
                    ),
                ),
                ("name", models.CharField(help_text="Platform name", max_length=255)),
                ("tagline", models.CharField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="platform/logo/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="platform/favicon/"
                    ),
                ),
                ("primary_color", models.CharField(default="#000000", max_length=7)),
                ("secondary_color", models.CharField(default="#ffffff", max_length=7)),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Profile",
                "verbose_name_plural": "Platform Profiles",
                "db_table": "platform_profile",
            },
        ),
        migrations.AddIndex(
            model_name="businessaccount",
            index=models.Index(fields=["slug"], name="business_ac_slug_a7994e_idx"),
        ),
        migrations.AddIndex(
            model_name="businessaccount",
            index=models.Index(
                fields=["status", "is_deleted"], name="business_ac_status_98a31e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessaccount",
            index=models.Index(
                fields=["verification_status"], name="business_ac_verific_d403f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessaccount",
            index=models.Index(
                fields=["country"], name="business_ac_country_82207a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", 1)),
                name="platform_account_singleton",
            ),
        ),
    ]
