# Generated by Django 5.1.15 on 2026-03-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_explore_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of members allowed. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum number of members allowed. 0 = unlimited.'),
        ),
    ]
