# Generated by Django 5.1.15 on 2026-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_add_member_quota_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessaccount",
            name="open_member_request",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether users can send membership requests to this business.",
            ),
        ),
        migrations.AddField(
            model_name="platformaccount",
            name="open_member_request",
            field=models.BooleanField(
                default=False,
                help_text="Whether users can send membership requests to the platform.",
            ),
        ),
    ]
