# Generated by Django 5.1.15 on 2026-01-25 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g., 'welcome', 'password_reset')",
                        max_length=100,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line. Supports {{ variables }}",
                        max_length=255,
                    ),
                ),
                (
                    "html_body",
                    models.TextField(
                        help_text="HTML email content. Supports {{ variables }}"
                    ),
                ),
                (
                    "text_body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text fallback. Auto-generated from HTML if empty.",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining expected variables. Example: {'user_name': {'type': 'string', 'required': true}}",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal description for admins"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Category for organization (auth, transactional, marketing)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive templates cannot be used"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number (new row created on each edit)",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True for the latest version of each template",
                    ),
                ),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "db_table": "email_templates",
                "ordering": ["category", "name", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_template_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("name",),
                        name="unique_current_template",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_email", models.EmailField(db_index=True, max_length=254)),
                ("from_email", models.EmailField(max_length=254)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                (
                    "template_name",
                    models.CharField(
                        help_text="Template name at time of send", max_length=100
                    ),
                ),
                (
                    "template_version",
                    models.PositiveIntegerField(
                        default=1, help_text="Template version at time of send"
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("html_body", models.TextField()),
                ("text_body", models.TextField(blank=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variables used to render template",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Provider message ID (SES Message-ID)",
                        max_length=255,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("max_retries", models.PositiveSmallIntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("complained_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bounce_type",
                    models.CharField(
                        blank=True, help_text="permanent/transient", max_length=20
                    ),
                ),
                (
                    "bounce_subtype",
                    models.CharField(
                        blank=True,
                        help_text="e.g., General, NoEmail, Suppressed",
                        max_length=50,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="email.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "email log",
                "verbose_name_plural": "email logs",
                "db_table": "email_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_email", "created_at"],
                        name="emaillogs_to_created_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="emaillogs_status_created_idx",
                    ),
                    models.Index(
                        fields=["template_name", "created_at"],
                        name="emaillogs_tpl_created_idx",
                    ),
                    models.Index(
                        fields=["message_id"], name="emaillogs_message_id_idx"
                    ),
                    models.Index(
                        condition=models.Q(("status", "failed")),
                        fields=["next_retry_at"],
                        name="emaillogs_failed_retry_idx",
                    ),
                ],
            },
        ),
    ]
