# Generated by Django 5.1.15 on 2026-03-20 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('business', 'Business'), ('platform', 'Platform')], db_index=True, max_length=20)),
                ('scope_id', models.UUIDField(blank=True, db_index=True, help_text='Null for global scope, UUID for org scope', null=True)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat')], max_length=20)),
                ('name', models.CharField(blank=True, default='', help_text='Group name (empty for DMs)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Group description (empty for DMs)')),
                ('created_by_type', models.CharField(choices=[('user', 'User'), ('business', 'Business'), ('platform', 'Platform')], max_length=20)),
                ('created_by_id', models.UUIDField()),
                ('last_message_id', models.UUIDField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=200)),
                ('last_message_sender_type', models.CharField(blank=True, default='', max_length=20)),
                ('last_message_sender_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'chat_conversation',
                'ordering': ['-last_message_at', '-created_at'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'is_active'], name='chat_conv_scope_active_idx'), models.Index(fields=['scope_type', 'scope_id', 'last_message_at'], name='chat_conv_scope_lastmsg_idx'), models.Index(fields=['conversation_type', 'scope_type', 'scope_id'], name='chat_conv_type_scope_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('blocked_type', models.CharField(choices=[('user', 'User'), ('business', 'Business'), ('platform', 'Platform')], max_length=20)),
                ('blocked_id', models.UUIDField()),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_block',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked_type', 'blocked_id'], name='chat_block_blocker_idx'), models.Index(fields=['blocked_type', 'blocked_id'], name='chat_block_blocked_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked_type', 'blocked_id'), name='unique_chat_block')],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('user', 'User'), ('business', 'Business'), ('platform', 'Platform')], max_length=20)),
                ('participant_id', models.UUIDField()),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20)),
                ('request_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored'), ('blocked', 'Blocked')], default='none', max_length=20)),
                ('last_delivered_message_id', models.UUIDField(blank=True, null=True)),
                ('last_seen_message_id', models.UUIDField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_chat_participants', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_chat_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation_participant',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participant_type', 'participant_id', 'is_active'], name='chat_part_type_id_active_idx'), models.Index(fields=['conversation', 'is_active'], name='chat_part_conv_active_idx'), models.Index(fields=['participant_type', 'participant_id', 'request_status'], name='chat_part_request_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('conversation', 'participant_type', 'participant_id'), name='unique_active_participant')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('business', 'Business'), ('platform', 'Platform')], max_length=20)),
                ('sender_id', models.UUIDField()),
                ('acting_user_id', models.UUIDField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('system', 'System')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='For rich content types (url preview, file info, etc.)')),
                ('sequence_number', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('edited', 'Edited'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_content', models.TextField(blank=True, default='', help_text='Preserved on edit/delete for moderation audit')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='chat_msg_conv_created_idx'), models.Index(fields=['conversation', 'sequence_number'], name='chat_msg_conv_seq_idx'), models.Index(fields=['sender_type', 'sender_id'], name='chat_msg_sender_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'sequence_number'), name='unique_message_sequence')],
            },
        ),
    ]
