# Generated by Django 5.1.15 on 2026-03-20 09:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_seed_chat_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content_type",
            field=models.CharField(
                choices=[("text", "Text"), ("system", "System"), ("image", "Image")],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(choices=[("image", "Image")], max_length=20),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_attachment",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["message"], name="chat_attach_msg_idx"),
                    models.Index(fields=["conversation"], name="chat_attach_conv_idx"),
                    models.Index(
                        condition=models.Q(("message__isnull", True)),
                        fields=["message"],
                        name="chat_attach_orphan_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("like", "👍"),
                            ("heart", "❤️"),
                            ("laugh", "😂"),
                            ("wow", "😮"),
                            ("sad", "😢"),
                            ("angry", "😡"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_reaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["message"], name="chat_reaction_msg_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "user", "reaction"),
                        name="unique_message_user_reaction",
                    )
                ],
            },
        ),
    ]
